name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build_android:
      runs-on: ubuntu-latest
      container:
        # trying to be close to the f-droid build to detect failures early
        image: registry.gitlab.com/fdroid/fdroidserver:buildserver-bullseye
      env:
        ANDROID_HOME: /opt/android-sdk
      steps:

        - name: apt update
          run: sudo apt update

        - name: Install jq
          run: sudo apt install jq

        - name: Install xz-utils
          run: sudo apt install xz-utils

        - name: Check out repository code
          uses: actions/checkout@v3
          with:
            submodules: recursive

        # Tags are required for Flutter to know its own version and check constraints
        - run: git -C ./flutter fetch --tags
          
        - run: ./flutter/bin/flutter config --no-analytics

        - run: ./flutter/bin/flutter --version

        - name: Build Android APK
          env:
            SIGNING_KEY_PWD: ${{ secrets.SIGNING_KEY_PWD }}
          run: ./flutter/bin/flutter build apk --flavor ci

        - name: Upload Android apk
          uses: actions/upload-artifact@v3
          with:
            name: Android apk
            path: ./build/app/outputs/flutter-apk/app-ci-release.apk
